return {"Trigger",
	{"TriggerName","TestTrigger"},
	{"True"},
	{"Event",
		{"TimeCycle",{"Number",10}}
	},
	{"Condition",
		{"NumberEqual",
			{"Add",
				{"GlobalNumber",
					{"GlobalName","var"}
				},
				{"Number",3},
			},
			{"Number",10}
		},
		{"True"}
	},
	{"Action",
		{"SetLocalNumber",
			{"LocalName","num"},
			{"Number",3}
		},
		{"If",
			{"And",
				{"NumberEqual",
					{"LocalNumber",
						{"LocalName","num"}
					},
					{"Number",3}
				},
				{"True"}
			},
			{"Action",
				{"Loopi",
					{"Number",3},
					{"Number",10},
					{"Number",1},
					{"Action",
						{"Sleep",
							{"Number",10}
						},
						{"Print",
							{"String","hello"}
						}
					}
				}
			},
			{"Action",
				{"DoNothing"}
			}
		},
		{"DoNothing"}
	}
}
